USE [BD_Cot4]
GO
/****** Object:  StoredProcedure [dbo].[FICO_ObtieneCobertura]    Script Date: 10/09/2018 10:23:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Miguel Rivas>
-- Create date: <12/12/2017>
-- Description:	<Obtiene informacion de cotización>
-- =============================================
ALTER PROCEDURE [dbo].[FICO_ObtieneCobertura] 
	@idCotizacion AS INT
AS
BEGIN
 SELECT 
 AMPARADAS.DES_AMPARADAS, 
 CONVERT(varchar(20), CONVERT(money, AMPARADAS.SUM_ASEG),1) AS SUM_ASEG, 
 CASE WHEN AMPARADAS.AMPARADA ='AMPARADA_AC' 
 	THEN  CASE WHEN BD_COTIZACION.ACCE = 0 
 		THEN 'EXCLUIDA' 
 		ELSE '$' + ' ' + CONVERT(varchar(20), CONVERT(money, BD_COTIZACION.ACCE),1) 
 		END 
 	ELSE CASE  WHEN AMPARADAS.AMPARADA ='EXCLUIDA' 
 		THEN 'EXCLUIDA' 
 		ELSE  CASE  WHEN AMPARADAS.AMPARADA ='AMPARADA_VA' 
 			THEN '$' + ' ' + CONVERT(varchar(20), CONVERT(money, CASE WHEN ISNULL(BD_COTIZACION.IS_PRECIOM,0) = 1 THEN N_PRECIO ELSE CASE WHEN [DBO].[GETSUBSIDIOCOTIZACION] (BD_COTIZACION.ID_COTIZACION,1,CAT_PLAZO.DES_PLAZO) > 0 THEN BD_COTIZACION.PRECIO - [DBO].[GETSUBSIDIOCOTIZACION] (BD_COTIZACION.ID_COTIZACION,1,CAT_PLAZO.DES_PLAZO) ELSE N_PRECIO END END),1) 
 			ELSE CASE WHEN AMPARADAS.AMPARADA ='AMPARADAB' 
 				THEN CASE WHEN AMPARADAS.SUM_ASEG > 100 OR AMPARADAS.SUM_ASEG < 0 
 					THEN 'ERROR %' 
 					ELSE '$' + ' ' + CONVERT(varchar(20),CONVERT(money,(CASE WHEN ISNULL(BD_COTIZACION.IS_PRECIOM,0) = 1 
 						THEN N_PRECIO 
 						ELSE CASE WHEN [dbo].[getSubsidioCotizacion] (BD_COTIZACION.ID_COTIZACION,1,CAT_PLAZO.des_plazo) > 0 
 							THEN BD_COTIZACION.PRECIO - [dbo].[getSubsidioCotizacion] (BD_COTIZACION.ID_COTIZACION,1,CAT_PLAZO.des_plazo) 
 							ELSE N_PRECIO 
 							END 
 						END	* ((CONVERT(numeric(14,4),AMPARADAS.SUM_ASEG)/100)))),1) 
 					END	
 				ELSE CASE  WHEN AMPARADAS.SUM_ASEG > 0 
 					THEN '$' + ' ' + CONVERT(varchar(20), CONVERT(money, AMPARADAS.SUM_ASEG),1) 
 					ELSE 'AMPARADA' 
 					END 
 				END 
 			END 
 		END 
 	END AS SUM_ASEG1, 
 AMPARADAS.DEDUCIBLE, 
 AMPARADAS.PRIMAS
 FROM BD_COTIZACION 
 INNER JOIN AMPARADAS ON BD_COTIZACION.N_COBERTURA = AMPARADAS.ID_COBERTURA 
 INNER JOIN CAT_PLAZO ON BD_COTIZACION.N_PLAZO = CAT_PLAZO.ID_PLAZO 
 WHERE BD_COTIZACION.ID_COTIZACION = @idCotizacion
 AND AMPARADAS.ID_STATUS = 1
 AND BD_COTIZACION.ID_USO = AMPARADAS.ID_USO
 ORDER BY AMPARADAS.cve

END